name: desafio_yandeh_web
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_modular: ^6.3.4
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  path_drawing: ^1.0.1
  intl: ^0.19.0
  dio: ^5.7.0
  talker_dio_logger: ^4.4.1
  video_player: ^2.9.1
  chewie: ^1.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/images/logo-loading.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/logo-loading.png"
    background_color: "#FFF4F4FA"
    theme_color: "#FFF4F4FA"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - ./assets/
    - ./assets/sections-with-products.json
    - ./assets/images/logo-app.png
    - ./assets/images/logo-loading.png
    - ./assets/images/yandeh-logo.png
    - ./assets/images/background-app-web.png
    - ./assets/images/tomate.png
    - ./assets/images/bandeja-vagem.png
    - ./assets/svgs/cart.svg
    - ./assets/videos/home.mp4
    - ./assets/videos/queridinhos.mp4
    - ./assets/videos/hortifruti.mp4
